Console.WriteLine("Ako sa voláš?");
string? meno = Console.ReadLine();
Console.WriteLine($"Ahoj,{meno}! Kolko mas rokov?");
string vstup = Console.ReadLine() ?? "0";
int vek = int.Parse(vstup);
Console.WriteLine("Aha, mas teda 15 rokov");
Console.WriteLine("Ake je tvoje oblubune jedlo?");
string jedlo = Console.ReadLine();
Console.WriteLine($"Hmmm, {jedlo} to znie skvele!");
Console.WriteLine("Aky mas dns den?");
string den = Console.ReadLine();
Console.WriteLine($"Tak to mas skvele!");
Console.WriteLine("Kolko za to dostanem za snahu?");
string text = Console.ReadLine();
Console.WriteLine("To je zle! Skus nieco ine!");
