Console.WriteLine("Ako sa voláš?");
string? meno = Console.ReadLine();
Console.WriteLine($"Ahoj,{meno}! Kolko mas rokov?");
string vstup = Console.ReadLine() ?? "0";
int vek = int.Parse(vstup);
Console.WriteLine("Aha, mas teda 15 rokov");
Console.WriteLine("Ake je tvoje oblubune jedlo?");
string jedlo = Console.ReadLine();
Console.WriteLine($"Hmmm, {jedlo} to znie skvele!");
Console.WriteLine("Aky mas dns den?");
string den = Console.ReadLine();
Console.WriteLine($"Tak to mas skvele!");
Console.WriteLine("Preco sa rozpravas s robotom?");
string text = Console.ReadLine();
Console.WriteLine("Nemyslis ze si na tom dost zle ked sa musis rozpavat so mnou?");
string text1 = Console.ReadLine();
Console.WriteLine("Aka je tvoja oblubena farba?");
string farba = Console.ReadLine();
Console.WriteLine($"Hmm, {farba}? Ja poznam aj krajsie ale tak je to tvoja vec. Kazdemu sa paci nieco ine.");
Console.WriteLine($"Tak, to by bolo zatial vsetko. Pokracovanie nabuduce.");
Console.WriteLine("Kolko dostanem cash za tento projekt?");
string text2= Console.ReadLine();
Console.WriteLine("Tak neni to moc ale na zaciatok staci!");